// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

public class UnityToIos
{
	[DllImport("__Internal")]
	private static extern void _RGToIos(string key,string value);

	public static void ToIos(string key,string value){
		_RGToIos(key,value);
	}
}


